server:
  port: 8760

spring:
  application:
    name: zuul-gateway

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

zuul:
  routes:
    clientService:
      path: /client-service/**
      serviceId: client-service

clientService:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule
    NFLoadBalancerClassName: com.netflix.loadbalancer.DynamicServerListLoadBalancer