server:
  port: 8003

spring:
  application:
    name: client-service


eureka:
#  instance:
#    secure-virtual-host-name: client-service
#    virtual-host-name: client-service
#    appname: client-service
  client:
    registry-refresh-single-vip-address: client-service
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}